.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH osssmrc 5 "2013/02/22" "osssm-1.16" 
.SH NAME
osssmrc \- APEL/SSM Openstack connector (osssm) configuration file

.SH DESCRIPTION
This manual describes the configuration items of the APEL/SSM Openstack connector.

.SH CONFIGURATION PARAMETERS
The configuration file is made of a single section [Main].

.IP \fBkeystone_api_url\fR
  Openstack keystone access URL
  example: http://host.domain.tld:portnumber/v2.0

.IP \fBuser\fR
  User used for accessing Nova API. That user has to be part of all tenants for which accounting is requested with a role allowing to retrieve usage records (rule compute_extension:simple_tenant_usage:list in /etc/nova/policy.json).

.IP \fBpassword\fR
  Password for accounting user 

.IP \fBlogfile_path\fR
  path to osssm logfile
  example: /var/log/osssm.log

.IP \fBspooldir_path\fR
  path to osssm spool directory (where the buffered usage records are stored)
  example: /var/spool/osssm

.IP \fBdebug_level\fR
  set the logging level
  example: DEBUG|INFO

.IP \fBtenants\fR
  keystone tenants for which VM accounting has to be retrieved, separated by commas. Whitespaces are allowed in tenant names.
  example: a first tenant, a second one
 
.IP \fBgocdb_sitename\fR
  the sitename reported into the accounting records. It should match the GOCDB sitename.

.IP \fBcloud_type\fR
  cloud manager reported into the accounting records 
  example: Openstack

.IP \fBssm_input_header\fR
  the header of the SSM input file
  example: APEL-cloud-message: v0.1

.IP \fBssm_input_sep\fR
  the records separator used in the SSM input file
  example: %%

.IP \fBssm_input_path\fR
  path to the SSM input base directory
  example: /var/spool/apel/outgoing

.SH "AUTHOR(S)"
.na
.nf
Mattieu Puel @ CC-IN2P3 FR


